project:
  type: website

website:
  title: "Introduction to Version Control"
  navbar:
    left:
      - href: index.qmd
        text: About The Workshop
      - text: "Pre-Workshop Materials"  
        menu:
         - pre-workshop/software-install.qmd
         - pre-workshop/assignment.qmd
      - text: "Slides"
        menu:
        - text: "May 23, 2024"
          href: slides/2024-05-03-bcstats-vc-git-hub.pptx
          target: "_blank"
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Getting Started"
        contents:
           - course-outline.qmd
      - section: "Course Sections"
        contents:
          - materials/01-what-is-vc.qmd
          - materials/02-working-local.qmd
          - materials/03-remote-hosting.qmd
          - materials/04-bcgov-org.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3

editor: visual

execute:
  freeze: auto

