project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Version Control"
  navbar:
    left:
      - href: index.qmd
        text: About The Workshop
      - text: "Pre-Workshop Materials"  
        menu:
         - pre-workshop/software-install.qmd
         - pre-workshop/assignment.qmd
      - text: "Slides"
        menu:
        - text: "1. What is Version Control"
          href: 01-what-is-vc.qmd
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Getting Started"
        contents:
           - course-outline.qmd
      - section: "Course Sections"
        contents:
          - 01-what-is-vc.qmd
          - 02-working-local.qmd
          - 03-remote-hosting.qmd
          - 04-bcgov-org.qmd
  


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

